/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

//import bean.Cliente;
//import bean.Funcionarios;
//import bean.Vendas;
//import dao.Vendas_DAO;
//import dao.Cliente_DAO;
//import dao.Funcionarios_DAO;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import tools.Util;

/**
 *
 * @author ASUS
 */
public class JDlgVendas extends javax.swing.JDialog {

    private boolean incluindo;
    //private Vendas_DAO venda_DAO;
   // Vendas venda;

    public JDlgVendas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
      //  Cliente_DAO cliente_DAO = new Cliente_DAO();
       // List lista = cliente_DAO.listAll();
      //  for (int i = 0; i < lista.size(); i++) {
          //  Cliente cliente = (Cliente) lista.get(i);
          //  jCboCliente.addItem(cliente);
        //}
       // Funcionarios_DAO funcionarios_DAO = new Funcionarios_DAO();
      //  List listaFUN = funcionarios_DAO.listAll();
       // for (int f = 0; f < listaFUN.size(); f++) {
       //     Funcionarios funcionarios = (Funcionarios) listaFUN.get(f);
//     jCboVendedor.addItem(funcionarios);
     //   }

        setLocationRelativeTo(null);
        setTitle("Vendas");
       // desabilitar();
        jBtnIncluir.setEnabled(true);
        jBtnPesquisar.setEnabled(true);
    }

  /*  public void habilitar() {
        jTxtIdVenda.setEnabled(true);
        jFmtDataVenda.setEnabled(true);
        jCboCliente.setEnabled(true);
        jCboVendedor.setEnabled(true);
        jTxtTotal.setEnabled(true);

        jBtnAlteratable.setEnabled(true);
        jBtnCancelar.setEnabled(true);
        jBtnConfirmar.setEnabled(true);
        jBtnExcluir.setEnabled(true);
        jBtnIncluir.setEnabled(true);
        jBtnPesquisar.setEnabled(true);
        jBtnIncluirtable.setEnabled(true);
        jBtnAlteratable.setEnabled(true);
        jBtnExluirtable.setEnabled(true);
    }

    public void desabilitar() {
        jTxtIdVenda.setEnabled(false);
        jFmtDataVenda.setEnabled(false);
        jCboCliente.setEnabled(false);
        jCboVendedor.setEnabled(false);
        jTxtTotal.setEnabled(false);

        jBtnAltera.setEnabled(false);
        jBtnCancelar.setEnabled(false);
        jBtnConfirmar.setEnabled(false);
        jBtnExcluir.setEnabled(false);
        jBtnIncluir.setEnabled(false);
        jBtnPesquisar.setEnabled(false);
        jBtnIncluirtable.setEnabled(false);
        jBtnAlteratable.setEnabled(false);
        jBtnExluirtable.setEnabled(false);
    }

    public void limparDados() {
        jTxtIdVenda.setText("");
        jFmtDataVenda.setText("");
        jCboCliente.setSelectedIndex(-1);
        jCboVendedor.setSelectedIndex(-1);
        jTxtTotal.setText("");
    }

    public void beanView(Vendas vendas) {
        String valor = String.valueOf(vendas.getIdVenda());
        jTxtIdVenda.setText(valor);
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        jFmtDataVenda.setText(formato.format(vendas.getDataVenda()));
        jCboCliente.setSelectedIndex(vendas.getIdCliente());
        jCboVendedor.setSelectedIndex(vendas.getIdFuncionarios());
        jTxtTotal.setText(String.valueOf(vendas.getTotal()));

    }

    private Vendas viewBean() {
        Vendas vendas = new Vendas();
        int id = Integer.valueOf(jTxtIdVenda.getText());
        vendas.setIdVenda(id);
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        try {
            vendas.setDataVenda(formato.parse(jFmtDataVenda.getText()));
        } catch (ParseException ex) {

            //Logger.getLogger(jDlgVenda.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Erro cabeçudo:" + ex.getMessage());
        }
        Cliente clientes = (Cliente) jCboCliente.getSelectedItem();
        vendas.setIdCliente(clientes.getidCliente());

        Funcionarios funcionarios = (Funcionarios) jCboVendedor.getSelectedItem();
        vendas.setIdFuncionarios(funcionarios.getIdFuncionario());

        String textoTotal = jTxtTotal.getText();
        double total = Double.parseDouble(textoTotal);
        vendas.setTotal(total);

        return vendas;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTxtTotal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTxtIdVenda = new javax.swing.JTextField();
        jFmtDataVenda = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jCboCliente = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jCboVendedor = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jBtnIncluir = new javax.swing.JButton();
        jBtnExcluir = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jBtnAlteratable = new javax.swing.JButton();
        jBtnPesquisar = new javax.swing.JButton();
        jBtnConfirmar = new javax.swing.JButton();
        jBtnIncluirtable = new javax.swing.JButton();
        jBtnExluirtable = new javax.swing.JButton();
        jBtnAltera = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setText("Data da venda");

        jLabel3.setText("Valor total");

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel4.setText("Vendas");

        jLabel5.setText("Id Venda");

        try {
            jFmtDataVenda.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel6.setText("Cliente");

        jCboCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCboClienteActionPerformed(evt);
            }
        });

        jLabel7.setText("Vendedor");

        jCboVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCboVendedorActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jBtnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/adicionar3(1).png"))); // NOI18N
        jBtnIncluir.setText("Incluir");
        jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirActionPerformed(evt);
            }
        });

        jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/excluir2 (2).png"))); // NOI18N
        jBtnExcluir.setText("Excluir");
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirActionPerformed(evt);
            }
        });

        jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar2.png"))); // NOI18N
        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        jBtnAlteratable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        jBtnAlteratable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlteratableActionPerformed(evt);
            }
        });

        jBtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jBtnPesquisar.setText("Pesquisar");
        jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisarActionPerformed(evt);
            }
        });

        jBtnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/confirmacao2.png"))); // NOI18N
        jBtnConfirmar.setText("Confirmar");
        jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmarActionPerformed(evt);
            }
        });

        jBtnIncluirtable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/adicionar3(1).png"))); // NOI18N
        jBtnIncluirtable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirtableActionPerformed(evt);
            }
        });

        jBtnExluirtable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/excluir2 (2).png"))); // NOI18N
        jBtnExluirtable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExluirtableActionPerformed(evt);
            }
        });

        jBtnAltera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        jBtnAltera.setText("Alterar");
        jBtnAltera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlteraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtIdVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jFmtDataVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCboCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCboVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addGap(53, 53, 53)
                                            .addComponent(jLabel6)
                                            .addGap(68, 68, 68)
                                            .addComponent(jLabel7))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jTxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jBtnIncluirtable, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnAlteratable, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jBtnExluirtable, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnIncluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnAltera)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnPesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnConfirmar)))
                .addGap(0, 77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtIdVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFmtDataVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCboCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCboVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnIncluirtable)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnAlteratable, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jBtnExluirtable))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnConfirmar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnCancelar)
                        .addComponent(jBtnExcluir)
                        .addComponent(jBtnIncluir)
                        .addComponent(jBtnAltera, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCboClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCboClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCboClienteActionPerformed

    private void jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirActionPerformed
        // TODO add your handling code here:
       // habilitar();
       // jBtnPesquisar.setEnabled(false);
       // jBtnExcluir.setEnabled(false);
        //jBtnAlteratable.setEnabled(false);
        //jBtnIncluir.setEnabled(false);
    }//GEN-LAST:event_jBtnIncluirActionPerformed

    private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirActionPerformed

        int resp = JOptionPane.showConfirmDialog(null, "Deseja excluir o registro?",
                "Exclusão", JOptionPane.YES_NO_OPTION);
        if (resp == JOptionPane.YES_OPTION) {
            /*Vendas Vendas = viewBean();
            Vendas_DAO Vendas_DAO = new Vendas_DAO();
            Vendas_DAO.delete(Vendas);
            JOptionPane.showMessageDialog(null, "Exclusão feita com sucesso!.");
*/
        } else {
            JOptionPane.showMessageDialog(null, "Exclusão cancelada.");
        }

        //limparDados();
        Util.limparCampos(jTxtIdVenda,jFmtDataVenda,jCboCliente, jCboVendedor, jTxtTotal, jBtnAltera, jBtnAlteratable, jBtnCancelar, jBtnConfirmar, jBtnExcluir, jBtnExluirtable, jBtnIncluir, jBtnIncluirtable, jBtnPesquisar);
        //desabilitar();
        Util.habilitar(false,jTxtIdVenda,jFmtDataVenda,jCboCliente, jCboVendedor, jTxtTotal, jBtnAltera, jBtnAlteratable, jBtnCancelar, jBtnConfirmar, jBtnExcluir, jBtnExluirtable, jBtnIncluir, jBtnIncluirtable, jBtnPesquisar);
       
        jBtnIncluir.setEnabled(true);
        jBtnPesquisar.setEnabled(true);
    }//GEN-LAST:event_jBtnExcluirActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        // TODO add your handling code here:
        //desabilitar();
        jBtnIncluir.setEnabled(true);
        jBtnPesquisar.setEnabled(true);

       // limparDados();
       Util.limparCampos(jTxtIdVenda,jFmtDataVenda,jCboCliente, jCboVendedor, jTxtTotal);
       

    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jBtnAlteratableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlteratableActionPerformed

       // desabilitar();
       // limparDados();
       Util.limparCampos(jTxtIdVenda,jFmtDataVenda,jCboCliente, jCboVendedor, jTxtTotal);
       Util.habilitar(false, jTxtIdVenda,jFmtDataVenda,jCboCliente, jCboVendedor, jTxtTotal, jBtnAltera, jBtnAlteratable, jBtnCancelar, jBtnConfirmar, jBtnExcluir, jBtnExluirtable, jBtnIncluir, jBtnIncluirtable, jBtnPesquisar);
       
        jBtnIncluir.setEnabled(true);
        jBtnPesquisar.setEnabled(true);
    }//GEN-LAST:event_jBtnAlteratableActionPerformed

    private void jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisarActionPerformed
        // TODO add your handling code here:
        jBtnPesquisar.setEnabled(true);
       /* JDlgPesquisaVendas jDlgPesquisaVendas = new JDlgPesquisaVendas(null, true);
        jDlgPesquisaVendas.setTitle("Pesquisa de produtos");
        jDlgPesquisaVendas.setTelaAnterior(this);
        jDlgPesquisaVendas.setVisible(true);*/
        //habilitar();
        Util.habilitar(true,jTxtIdVenda,jFmtDataVenda,jCboCliente, jCboVendedor, jTxtTotal, jBtnAltera, jBtnAlteratable, jBtnCancelar, jBtnConfirmar, jBtnExcluir, jBtnExluirtable, jBtnIncluir, jBtnIncluirtable, jBtnPesquisar);
       
        jBtnConfirmar.setEnabled(false);
        jBtnIncluir.setEnabled(false);
        jBtnAltera.setEnabled(true);
    }//GEN-LAST:event_jBtnPesquisarActionPerformed

    private void jBtnIncluirtableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirtableActionPerformed

        /*JDlgVendasProdutos vendas = new JDlgVendasProdutos(null, true);
        vendas.setTitle("Inclusao de produtos");
        vendas.setLocationRelativeTo(null);
        vendas.setVisible(true);*/

    }//GEN-LAST:event_jBtnIncluirtableActionPerformed

    private void jBtnExluirtableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExluirtableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnExluirtableActionPerformed

    private void jBtnAlteraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlteraActionPerformed
        int resp = JOptionPane.showConfirmDialog(null, "Deseja alterar o registro?",
                "Alterar", JOptionPane.YES_NO_OPTION);
        if (resp == JOptionPane.YES_OPTION) {
            /*Vendas Vendas = viewBean();
            Vendas_DAO Vendas_DAO = new Vendas_DAO();
            Vendas_DAO.update(Vendas);
            JOptionPane.showMessageDialog(null, "Registro atualizado com sucesso!");
        } else {
            JOptionPane.showMessageDialog(null, "Registro não encontrado!");*/
        }
        //desabilitar();
        //limparDados();
        Util.limparCampos(jTxtIdVenda,jFmtDataVenda,jCboCliente, jCboVendedor, jTxtTotal);
       Util.habilitar(false,jTxtIdVenda,jFmtDataVenda,jCboCliente, jCboVendedor, jTxtTotal, jBtnAltera, jBtnAlteratable, jBtnCancelar, jBtnConfirmar, jBtnExcluir, jBtnExluirtable, jBtnIncluir, jBtnIncluirtable, jBtnPesquisar);
       
        jBtnIncluir.setEnabled(true);
        jBtnPesquisar.setEnabled(true);
    }//GEN-LAST:event_jBtnAlteraActionPerformed

    private void jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmarActionPerformed
        // TODO add your handling code here:

       /* Vendas_DAO vendas_DAO = new Vendas_DAO();
        vendas_DAO.insert(viewBean());
        JOptionPane.showMessageDialog(null, "Venda registrada!");

*/
    }//GEN-LAST:event_jBtnConfirmarActionPerformed

    private void jCboVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCboVendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCboVendedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgVendas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgVendas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgVendas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgVendas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgVendas dialog = new JDlgVendas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAltera;
    private javax.swing.JButton jBtnAlteratable;
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnConfirmar;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnExluirtable;
    private javax.swing.JButton jBtnIncluir;
    private javax.swing.JButton jBtnIncluirtable;
    private javax.swing.JButton jBtnPesquisar;
    private javax.swing.JComboBox jCboCliente;
    private javax.swing.JComboBox jCboVendedor;
    private javax.swing.JFormattedTextField jFmtDataVenda;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTxtIdVenda;
    private javax.swing.JTextField jTxtTotal;
    // End of variables declaration//GEN-END:variables

}
