/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.MljfsClientes;
import bean.MljfsFuncionarios;
import bean.MljfsVendas;
import bean.MljfsVendasProdutos;
import controles.VendasProdutosControle;
import dao.ClienteDAO;
import dao.FuncionariosDAO;
import dao.VendasDAO;
import dao.VendasProdutosDAO;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import tools.Util;

/**
 *
 * @author Melany
 */
public class JDlgMljfsVendas extends javax.swing.JDialog {

    private boolean incluindo = true;
    private boolean alterando;
    VendasProdutosControle vendasProdutosControle = new VendasProdutosControle();

    public void setAlterando(boolean alterando) {
        this.alterando = alterando;
    }

    public boolean isIncluindo() {
        return incluindo;
    }

    public void setIncluindo(boolean incluindo) {
        this.incluindo = incluindo;
    }

    /**
     * Creates new form JDlgMljfsVendas
     */
    public JDlgMljfsVendas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);

        setLocationRelativeTo(null);
        Util.habilitar(false, jTxtIdPedido, jTxtTotal, jFmtData, jCboCliente, jCboVendedor, jTxtMetodoPagamento, jBtnCancelar, jBtnConfirmar, jBtnExcluir, jBtnAlterar, jBtnIncluirTb, jBtnExcluirTb, jBtnAlterarTb);
        Util.limparCampos(jTxtIdPedido, jTxtTotal, jFmtData, jCboCliente, jCboVendedor);

        List lista = new ArrayList();
        vendasProdutosControle.setList(lista);
        jTable1.setModel(vendasProdutosControle);

        ClienteDAO clienteDAO = new ClienteDAO();
        List listaClientes = clienteDAO.listAll();
        for (int i = 0; i < listaClientes.size(); i++) {
            jCboCliente.addItem((MljfsClientes) listaClientes.get(i));
        }
        FuncionariosDAO funcionarioDAO = new FuncionariosDAO();
        List listaFuncionario = funcionarioDAO.listAll();
        for (int i = 0; i < listaFuncionario.size(); i++) {
            jCboVendedor.addItem((MljfsFuncionarios) listaFuncionario.get(i));
        }
    }

    private MljfsVendas viewBean() {
        MljfsVendas vendas = new MljfsVendas();
        int id = Integer.valueOf(jTxtIdPedido.getText());
        vendas.setMljfsId(id);
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        try {
            vendas.setMljfsData(formato.parse(jFmtData.getText()));
        } catch (ParseException ex) {
            System.out.println("Erro :" + ex.getMessage());
        }
        MljfsClientes clientes = (MljfsClientes) jCboCliente.getSelectedItem();
        vendas.setMljfsClienteId(clientes.getMljfsId());

        MljfsFuncionarios funcionarios = (MljfsFuncionarios) jCboVendedor.getSelectedItem();
        vendas.setMljfsFkFuncionarios(funcionarios.getMljfsId());

        String textoTotal = jTxtTotal.getText();
        double total = Double.parseDouble(textoTotal);
        vendas.setMljfsValorTotal(total);

        vendas.setMljfsMetodoPagamento(jTxtMetodoPagamento.getText());

        return vendas;

    }

    public void beanView(MljfsVendas vendas) {
        String valor = String.valueOf(vendas.getMljfsId());
        jTxtIdPedido.setText(valor);
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        jFmtData.setText(formato.format(vendas.getMljfsData()));
        for (int i = 0; i < jCboCliente.getItemCount(); i++) {
        MljfsClientes cliente = jCboCliente.getItemAt(i);
        if (cliente.getMljfsId() == vendas.getMljfsClienteId()) {
            jCboCliente.setSelectedIndex(i);
        }
    }

    // Encontrar o vendedor no ComboBox e definir como selecionado
    for (int i = 0; i < jCboVendedor.getItemCount(); i++) {
        MljfsFuncionarios vendedor = jCboVendedor.getItemAt(i);
        if (vendedor.getMljfsId() == vendas.getMljfsFkFuncionarios()) {
            jCboVendedor.setSelectedIndex(i);
        }
    }
        jTxtTotal.setText(String.valueOf(vendas.getMljfsValorTotal()));
        jTxtMetodoPagamento.setText(vendas.getMljfsMetodoPagamento());
    }

    public int getSelectedRowProd() {
        return jTable1.getSelectedRow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTxtIdPedido = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jFmtData = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jCboCliente = new javax.swing.JComboBox<MljfsClientes>();
        jLabel4 = new javax.swing.JLabel();
        jCboVendedor = new javax.swing.JComboBox<MljfsFuncionarios>();
        jLabel5 = new javax.swing.JLabel();
        jTxtTotal = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jBtnIncluir = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jBtnPesquisar = new javax.swing.JButton();
        jBtnAlterar = new javax.swing.JButton();
        jBtnExcluir = new javax.swing.JButton();
        jBtnConfirmar = new javax.swing.JButton();
        jBtnIncluirTb = new javax.swing.JButton();
        jBtnAlterarTb = new javax.swing.JButton();
        jBtnExcluirTb = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTxtMetodoPagamento = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Id Venda");

        jLabel2.setText("Data");

        try {
            jFmtData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel3.setText("Cliente");

        jLabel4.setText("Vendedor");

        jLabel5.setText("Total");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jBtnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/adicionar3(1).png"))); // NOI18N
        jBtnIncluir.setText("Incluir");
        jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirActionPerformed(evt);
            }
        });
        jBtnIncluir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBtnIncluirKeyPressed(evt);
            }
        });
        jPanel1.add(jBtnIncluir);

        jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar2(1).png"))); // NOI18N
        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnCancelar);

        jBtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Pesquisa(1).png"))); // NOI18N
        jBtnPesquisar.setText("Pesquisar");
        jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisarActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnPesquisar);

        jBtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar_1(1).png"))); // NOI18N
        jBtnAlterar.setText("Alterar");
        jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnAlterar);

        jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/excluir2 (2)(1).png"))); // NOI18N
        jBtnExcluir.setText("Excluir");
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnExcluir);

        jBtnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/confirmacao2(1).png"))); // NOI18N
        jBtnConfirmar.setText("Confirmar");
        jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmarActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnConfirmar);

        jBtnIncluirTb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/adicionar2.png"))); // NOI18N
        jBtnIncluirTb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirTbActionPerformed(evt);
            }
        });

        jBtnAlterarTb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar_1(1).png"))); // NOI18N
        jBtnAlterarTb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarTbActionPerformed(evt);
            }
        });

        jBtnExcluirTb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir(1).png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel6.setText("Vendas");

        jLabel7.setText("Método de Pagamento");

        jTxtMetodoPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtMetodoPagamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTxtIdPedido, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jCboCliente, 0, 110, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jCboVendedor, 0, 110, Short.MAX_VALUE))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFmtData, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                    .addComponent(jLabel2)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(288, 288, 288)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jTxtTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTxtMetodoPagamento)))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnIncluirTb, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnAlterarTb, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnExcluirTb, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE)
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBtnAlterarTb, jBtnExcluirTb, jBtnIncluirTb});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtIdPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCboCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCboVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtMetodoPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnIncluirTb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnAlterarTb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnExcluirTb))))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jBtnAlterarTb, jBtnExcluirTb, jBtnIncluirTb});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirActionPerformed
        //habilitar();
        //incluindo = true;
        Util.habilitar(true, jTxtIdPedido, jTxtTotal, jFmtData, jCboCliente, jCboVendedor, jTxtMetodoPagamento, jBtnAlterar, jBtnCancelar, jBtnConfirmar, jBtnExcluir, jBtnIncluir, jBtnPesquisar, jBtnIncluirTb, jBtnExcluirTb, jBtnAlterarTb);
        Util.limparCampos(jTxtIdPedido, jTxtTotal, jFmtData, jCboCliente, jCboVendedor);
        jBtnAlterar.setEnabled(false);
        jBtnIncluir.setEnabled(false);
        jBtnExcluir.setEnabled(false);
        jBtnPesquisar.setEnabled(false);
    }//GEN-LAST:event_jBtnIncluirActionPerformed

    private void jBtnIncluirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBtnIncluirKeyPressed
        // TODO add your handling code here:
        Util.habilitar(true, jTxtIdPedido, jTxtTotal, jFmtData, jCboCliente, jTxtMetodoPagamento, jCboVendedor, jBtnAlterar, jBtnCancelar, jBtnConfirmar, jBtnExcluir, jBtnIncluir, jBtnPesquisar, jBtnIncluirTb, jBtnExcluirTb, jBtnAlterarTb);
    }//GEN-LAST:event_jBtnIncluirKeyPressed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        // TODO add your handling code here:
        //desabilitar();
        Util.habilitar(false, jTxtIdPedido, jTxtTotal, jFmtData, jCboCliente, jTxtMetodoPagamento, jCboVendedor, jBtnAlterar, jBtnCancelar, jBtnConfirmar, jBtnExcluir, jBtnIncluir, jBtnPesquisar, jBtnIncluirTb, jBtnExcluirTb, jBtnAlterarTb);
        jBtnIncluir.setEnabled(true);
        jBtnPesquisar.setEnabled(true);

        //limparDados();
        Util.limparCampos(jTxtIdPedido, jTxtTotal, jFmtData, jCboCliente, jTxtMetodoPagamento, jCboVendedor);
        Util.mensagem("Operação cancelada");
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisarActionPerformed
        // TODO add your handling code here:

        JDlgMljfsVendasPesquisa jDlgMljfsVendasPesquisa = new JDlgMljfsVendasPesquisa(null, true);
        jDlgMljfsVendasPesquisa.setTelaAnterior(this);
        jDlgMljfsVendasPesquisa.setVisible(true);
        Util.habilitar(true, jBtnAlterar, jBtnCancelar, jBtnConfirmar, jBtnExcluir, jBtnIncluirTb, jBtnExcluirTb, jBtnAlterarTb);
        jBtnIncluir.setEnabled(false);
        jBtnPesquisar.setEnabled(false);

    }//GEN-LAST:event_jBtnPesquisarActionPerformed

    private void jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarActionPerformed
        // TODO add your handling code here:
        //desabilitar();
        Util.habilitar(true, jTxtIdPedido, jTxtTotal, jFmtData, jCboCliente, jTxtMetodoPagamento, jCboVendedor, jBtnAlterar, jBtnCancelar, jBtnConfirmar, jBtnExcluir, jBtnIncluirTb, jBtnExcluirTb, jBtnAlterarTb);

        Util.habilitar(false, jBtnAlterar, jBtnExcluir, jBtnIncluir, jBtnPesquisar, jBtnIncluirTb, jBtnExcluirTb, jBtnAlterarTb);

        incluindo = false;
        //Util.limparCampos(jTxtId, jTxtNome, jTxtSobrenome, jTxtEmail, jFmtTelefone, jTxtEndereco, jTxtCidade, jTxtEstado, jFmtCep, jFmtdataNasc, jCboGenero, jCboEstadoCivil, jTxtProfissao, jTxtPais, jFmtDataCadastro, jTxtObservacoes);
    }//GEN-LAST:event_jBtnAlterarActionPerformed

    private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirActionPerformed
        // TODO add your handling code here:
        /*int resp = JOptionPane.showConfirmDialog(null, "Deseja excluir o registro?",
            "Exclusão", JOptionPane.YES_NO_OPTION);
        if (resp == JOptionPane.YES_OPTION) {
            MljfsClientes cliente = viewBean();
            ClienteDAO cliente_DAO = new ClienteDAO();
            cliente_DAO.delete(cliente);
            JOptionPane.showMessageDialog(null, "Exclusão bem sucedida!.");

        } else {
            JOptionPane.showMessageDialog(null, "Exclusão cancelada.");
        }*/

        //limparDados();
        //desabilitar();
        Util.habilitar(false, jTxtIdPedido, jTxtTotal, jFmtData, jCboCliente, jTxtMetodoPagamento, jCboVendedor, jBtnAlterar, jBtnCancelar, jBtnConfirmar, jBtnExcluir, jBtnIncluir, jBtnPesquisar, jBtnIncluirTb, jBtnExcluirTb, jBtnAlterarTb);
        Util.limparCampos(jTxtIdPedido, jTxtTotal, jFmtData, jCboCliente, jTxtMetodoPagamento, jCboVendedor);
        jBtnIncluir.setEnabled(true);
        jBtnPesquisar.setEnabled(true);
    }//GEN-LAST:event_jBtnExcluirActionPerformed

    private void jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmarActionPerformed
        MljfsVendas MljfsVendas = viewBean();
        VendasDAO vendaDAO = new VendasDAO();
        VendasProdutosDAO vendasprodutodao = new VendasProdutosDAO();
        MljfsVendasProdutos MljfsVendasProdutos = new MljfsVendasProdutos();
        MljfsVendas = viewBean();
        if (incluindo == true) {
            vendaDAO.insert(MljfsVendas);
            VendasProdutosDAO pedidosProdutosDAO = new VendasProdutosDAO();
            MljfsVendasProdutos pedidosProdutos;
            for (int linha = 0; linha < jTable1.getRowCount(); linha++) {
                pedidosProdutos = vendasProdutosControle.getBean(linha);
                pedidosProdutos.setMljfsVendas(MljfsVendas);
                pedidosProdutosDAO.insert(pedidosProdutos);
            }
            Util.mensagem("Venda adicionada com sucesso");
        } else {
            vendaDAO.update(MljfsVendas);
            //remover todos os pedidos produtos deste pedido

            //incluir todos os pedidosProduto que estao no jtable
            VendasProdutosDAO pedidosProdutosDAO = new VendasProdutosDAO();
            MljfsVendasProdutos pedidosProdutos;
            for (int linha = 0; linha < jTable1.getRowCount(); linha++) {
                pedidosProdutos = vendasProdutosControle.getBean(linha);
                pedidosProdutos.setMljfsVendas(MljfsVendas);
                pedidosProdutosDAO.insert(pedidosProdutos);
            }
            Util.mensagem("Venda alterada com sucesso");
        }
        Util.habilitar(false, jTxtIdPedido, jTxtTotal, jFmtData, jCboCliente, jTxtMetodoPagamento, jCboVendedor, jBtnAlterar, jBtnCancelar, jBtnConfirmar, jBtnExcluir, jBtnIncluir, jBtnPesquisar, jBtnIncluirTb, jBtnExcluirTb, jBtnAlterarTb);
        jBtnIncluir.setEnabled(true);
        jBtnPesquisar.setEnabled(true);
        Util.limparCampos(jTxtIdPedido, jFmtData, jCboCliente, jTxtMetodoPagamento, jCboVendedor, jTxtTotal);
        vendasProdutosControle.setList(new ArrayList());

        MljfsVendas = null;
    }//GEN-LAST:event_jBtnConfirmarActionPerformed

    private void jBtnIncluirTbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirTbActionPerformed
        // TODO add your handling code here:
        //Util.habilitar(false, jTxtIdPedido, jTxtTotal, jFmtData, jCboCliente, jCboVendedor, jBtnAlterar, jBtnCancelar, jBtnConfirmar, jBtnExcluir, jBtnIncluir, jBtnPesquisar, jBtnIncluirTb, jBtnExcluirTb, jBtnAlterarTb);
        JDlgVendasProduto jDlgVendasProduto = new JDlgVendasProduto(null, true);
        jDlgVendasProduto.setTitle("Incluir");
        jDlgVendasProduto.setTelaAnterior(this);
        jDlgVendasProduto.setVisible(true);
        setIncluindo(true);


    }//GEN-LAST:event_jBtnIncluirTbActionPerformed

    private void jBtnAlterarTbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarTbActionPerformed
        // TODO add your handling code here:

        JDlgVendasProduto jDlgVendasProduto = new JDlgVendasProduto(null, true);
        jDlgVendasProduto.setTitle("Alterar");
        jDlgVendasProduto.setIncluindo(incluindo); // Configura a variável incluindo na Tela
        int rowSel = jTable1.getSelectedRow();
        if (rowSel != -1) {
            MljfsVendasProdutos vendasProdutos = vendasProdutosControle.getBean(rowSel);
            jDlgVendasProduto.beanView(vendasProdutos);

            jDlgVendasProduto.setVisible(true);
        } else {
            Util.mensagem("Selecione um registro para alterar.");
        }

        setIncluindo(false);
    }//GEN-LAST:event_jBtnAlterarTbActionPerformed

    private void jTxtMetodoPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtMetodoPagamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtMetodoPagamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgMljfsVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgMljfsVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgMljfsVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgMljfsVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgMljfsVendas dialog = new JDlgMljfsVendas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAlterar;
    private javax.swing.JButton jBtnAlterarTb;
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnConfirmar;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnExcluirTb;
    private javax.swing.JButton jBtnIncluir;
    private javax.swing.JButton jBtnIncluirTb;
    private javax.swing.JButton jBtnPesquisar;
    private javax.swing.JComboBox<MljfsClientes> jCboCliente;
    private javax.swing.JComboBox<MljfsFuncionarios> jCboVendedor;
    private javax.swing.JFormattedTextField jFmtData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTxtIdPedido;
    private javax.swing.JTextField jTxtMetodoPagamento;
    private javax.swing.JTextField jTxtTotal;
    // End of variables declaration//GEN-END:variables
}
