package bean;
// Generated 16/09/2023 13:01:41 by Hibernate Tools 4.3.1



import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MljfsProdutos generated by hbm2java
 */
@Entity
@Table(name="mljfs_produtos"
    ,catalog="db_melany_salinas"
)
public class MljfsProdutos  implements java.io.Serializable {


     private int mljfsId;
     private String mljfsNome;
     private Double mljfsPreco;
     private Set mljfsVendasProdutoses = new HashSet(0);

    public MljfsProdutos() {
    }

	
    public MljfsProdutos(int mljfsId, String mljfsNome, Double mljfsPreco) {
        this.mljfsId = mljfsId;
        this.mljfsNome = mljfsNome;
        this.mljfsPreco = mljfsPreco;
    }
    public MljfsProdutos(int mljfsId, String mljfsNome, Double mljfsPreco, Set mljfsVendasProdutoses) {
       this.mljfsId = mljfsId;
       this.mljfsNome = mljfsNome;
       this.mljfsPreco = mljfsPreco;
       this.mljfsVendasProdutoses = mljfsVendasProdutoses;
    }
   
     @Id 

    
    @Column(name="mljfs_id", unique=true, nullable=false)
    public int getMljfsId() {
        return this.mljfsId;
    }
    
    public void setMljfsId(int mljfsId) {
        this.mljfsId = mljfsId;
    }

    
    @Column(name="mljfs_nome", nullable=false)
    public String getMljfsNome() {
        return this.mljfsNome;
    }
    
    public void setMljfsNome(String mljfsNome) {
        this.mljfsNome = mljfsNome;
    }

    
    @Column(name="mljfs_preco", nullable=false, precision=10)
    public Double getMljfsPreco() {
        return this.mljfsPreco;
    }
    
    public void setMljfsPreco(Double mljfsPreco) {
        this.mljfsPreco = mljfsPreco;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mljfsProdutos")
    public Set getMljfsVendasProdutoses() {
        return this.mljfsVendasProdutoses;
    }
    
    public void setMljfsVendasProdutoses(Set mljfsVendasProdutoses) {
        this.mljfsVendasProdutoses = mljfsVendasProdutoses;
    }




}


