package bean;
// Generated 05/12/2023 08:44:27 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MljfsClientes generated by hbm2java
 */
@Entity
@Table(name="mljfs_clientes"
    ,catalog="db_melany_salinas"
)
public class MljfsClientes  implements java.io.Serializable {


     private int mljfsId;
     private String mljfsNome;
     private String mljfsSobrenome;
     private String mljfsEmail;
     private String mljfsTelefone;
     private String mljfsEndereco;
     private String mljfsCidade;
     private String mljfsEstado;
     private String mljfsCep;
     private Date mljfsDataNascimento;
     private String mljfsGenero;
     private String mljfsEstadoCivil;
     private String mljfsProfissao;
     private String mljfsPais;
     private Date mljfsDataCadastro;
     private String mljfsObservacoes;

    public MljfsClientes() {
    }

	
    public MljfsClientes(int mljfsId, String mljfsNome) {
        this.mljfsId = mljfsId;
        this.mljfsNome = mljfsNome;
    }
    public MljfsClientes(int mljfsId, String mljfsNome, String mljfsSobrenome, String mljfsEmail, String mljfsTelefone, String mljfsEndereco, String mljfsCidade, String mljfsEstado, String mljfsCep, Date mljfsDataNascimento, String mljfsGenero, String mljfsEstadoCivil, String mljfsProfissao, String mljfsPais, Date mljfsDataCadastro, String mljfsObservacoes) {
       this.mljfsId = mljfsId;
       this.mljfsNome = mljfsNome;
       this.mljfsSobrenome = mljfsSobrenome;
       this.mljfsEmail = mljfsEmail;
       this.mljfsTelefone = mljfsTelefone;
       this.mljfsEndereco = mljfsEndereco;
       this.mljfsCidade = mljfsCidade;
       this.mljfsEstado = mljfsEstado;
       this.mljfsCep = mljfsCep;
       this.mljfsDataNascimento = mljfsDataNascimento;
       this.mljfsGenero = mljfsGenero;
       this.mljfsEstadoCivil = mljfsEstadoCivil;
       this.mljfsProfissao = mljfsProfissao;
       this.mljfsPais = mljfsPais;
       this.mljfsDataCadastro = mljfsDataCadastro;
       this.mljfsObservacoes = mljfsObservacoes;
    }
   
     @Id 

    
    @Column(name="mljfs_id", unique=true, nullable=false)
    public int getMljfsId() {
        return this.mljfsId;
    }
    
    public void setMljfsId(int mljfsId) {
        this.mljfsId = mljfsId;
    }

    
    @Column(name="mljfs_nome", nullable=false)
    public String getMljfsNome() {
        return this.mljfsNome;
    }
    
    public void setMljfsNome(String mljfsNome) {
        this.mljfsNome = mljfsNome;
    }

    
    @Column(name="mljfs_sobrenome")
    public String getMljfsSobrenome() {
        return this.mljfsSobrenome;
    }
    
    public void setMljfsSobrenome(String mljfsSobrenome) {
        this.mljfsSobrenome = mljfsSobrenome;
    }

    
    @Column(name="mljfs_email")
    public String getMljfsEmail() {
        return this.mljfsEmail;
    }
    
    public void setMljfsEmail(String mljfsEmail) {
        this.mljfsEmail = mljfsEmail;
    }

    
    @Column(name="mljfs_telefone", length=15)
    public String getMljfsTelefone() {
        return this.mljfsTelefone;
    }
    
    public void setMljfsTelefone(String mljfsTelefone) {
        this.mljfsTelefone = mljfsTelefone;
    }

    
    @Column(name="mljfs_endereco")
    public String getMljfsEndereco() {
        return this.mljfsEndereco;
    }
    
    public void setMljfsEndereco(String mljfsEndereco) {
        this.mljfsEndereco = mljfsEndereco;
    }

    
    @Column(name="mljfs_cidade")
    public String getMljfsCidade() {
        return this.mljfsCidade;
    }
    
    public void setMljfsCidade(String mljfsCidade) {
        this.mljfsCidade = mljfsCidade;
    }

    
    @Column(name="mljfs_estado")
    public String getMljfsEstado() {
        return this.mljfsEstado;
    }
    
    public void setMljfsEstado(String mljfsEstado) {
        this.mljfsEstado = mljfsEstado;
    }

    
    @Column(name="mljfs_cep", length=10)
    public String getMljfsCep() {
        return this.mljfsCep;
    }
    
    public void setMljfsCep(String mljfsCep) {
        this.mljfsCep = mljfsCep;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="mljfs_data_nascimento", length=10)
    public Date getMljfsDataNascimento() {
        return this.mljfsDataNascimento;
    }
    
    public void setMljfsDataNascimento(Date mljfsDataNascimento) {
        this.mljfsDataNascimento = mljfsDataNascimento;
    }

    
    @Column(name="mljfs_genero", length=20)
    public String getMljfsGenero() {
        return this.mljfsGenero;
    }
    
    public void setMljfsGenero(String mljfsGenero) {
        this.mljfsGenero = mljfsGenero;
    }

    
    @Column(name="mljfs_estado_civil", length=100)
    public String getMljfsEstadoCivil() {
        return this.mljfsEstadoCivil;
    }
    
    public void setMljfsEstadoCivil(String mljfsEstadoCivil) {
        this.mljfsEstadoCivil = mljfsEstadoCivil;
    }

    
    @Column(name="mljfs_profissao")
    public String getMljfsProfissao() {
        return this.mljfsProfissao;
    }
    
    public void setMljfsProfissao(String mljfsProfissao) {
        this.mljfsProfissao = mljfsProfissao;
    }

    
    @Column(name="mljfs_pais", length=100)
    public String getMljfsPais() {
        return this.mljfsPais;
    }
    
    public void setMljfsPais(String mljfsPais) {
        this.mljfsPais = mljfsPais;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="mljfs_data_cadastro", length=10)
    public Date getMljfsDataCadastro() {
        return this.mljfsDataCadastro;
    }
    
    public void setMljfsDataCadastro(Date mljfsDataCadastro) {
        this.mljfsDataCadastro = mljfsDataCadastro;
    }

    
    @Column(name="mljfs_observacoes")
    public String getMljfsObservacoes() {
        return this.mljfsObservacoes;
    }
    
    public void setMljfsObservacoes(String mljfsObservacoes) {
        this.mljfsObservacoes = mljfsObservacoes;
    }


public String toString(){
    return mljfsNome;
}

}


