package bean;
// Generated 16/09/2023 13:01:41 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MljfsUsuarios generated by hbm2java
 */
@Entity
@Table(name="mljfs_usuarios"
    ,catalog="db_melany_salinas"
)
public class MljfsUsuarios  implements java.io.Serializable {


     private int mljfsId;
     private String mljfsNome;
     private String mljfsSobrenome;
     private String mljfsEmail;
     private String mljfsCargo;
     private Double mljfsSalario;
     private Date mljfsDataNascimento;
     private String mljfsTelefone;
     private String mljfsSetor;
     private String mljfsSenha;

    public MljfsUsuarios() {
    }

	
    public MljfsUsuarios(int mljfsId, String mljfsNome) {
        this.mljfsId = mljfsId;
        this.mljfsNome = mljfsNome;
    }
    public MljfsUsuarios(int mljfsId, String mljfsNome, String mljfsSobrenome, String mljfsEmail, String mljfsCargo, Double mljfsSalario, Date mljfsDataNascimento, String mljfsTelefone, String mljfsSetor, String mljfsSenha) {
       this.mljfsId = mljfsId;
       this.mljfsNome = mljfsNome;
       this.mljfsSobrenome = mljfsSobrenome;
       this.mljfsEmail = mljfsEmail;
       this.mljfsCargo = mljfsCargo;
       this.mljfsSalario = mljfsSalario;
       this.mljfsDataNascimento = mljfsDataNascimento;
       this.mljfsTelefone = mljfsTelefone;
       this.mljfsSetor = mljfsSetor;
       this.mljfsSenha = mljfsSenha;
    }
   
     @Id 

    
    @Column(name="mljfs_id", unique=true, nullable=false)
    public int getMljfsId() {
        return this.mljfsId;
    }
    
    public void setMljfsId(int mljfsId) {
        this.mljfsId = mljfsId;
    }

    
    @Column(name="mljfs_nome", nullable=false)
    public String getMljfsNome() {
        return this.mljfsNome;
    }
    
    public void setMljfsNome(String mljfsNome) {
        this.mljfsNome = mljfsNome;
    }

    
    @Column(name="mljfs_sobrenome")
    public String getMljfsSobrenome() {
        return this.mljfsSobrenome;
    }
    
    public void setMljfsSobrenome(String mljfsSobrenome) {
        this.mljfsSobrenome = mljfsSobrenome;
    }

    
    @Column(name="mljfs_email")
    public String getMljfsEmail() {
        return this.mljfsEmail;
    }
    
    public void setMljfsEmail(String mljfsEmail) {
        this.mljfsEmail = mljfsEmail;
    }

    
    @Column(name="mljfs_cargo")
    public String getMljfsCargo() {
        return this.mljfsCargo;
    }
    
    public void setMljfsCargo(String mljfsCargo) {
        this.mljfsCargo = mljfsCargo;
    }

    
    @Column(name="mljfs_salario", precision=10)
    public Double getMljfsSalario() {
        return this.mljfsSalario;
    }
    
    public void setMljfsSalario(Double mljfsSalario) {
        this.mljfsSalario = mljfsSalario;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="mljfs_data_nascimento", length=10)
    public Date getMljfsDataNascimento() {
        return this.mljfsDataNascimento;
    }
    
    public void setMljfsDataNascimento(Date mljfsDataNascimento) {
        this.mljfsDataNascimento = mljfsDataNascimento;
    }

    
    @Column(name="mljfs_telefone", length=15)
    public String getMljfsTelefone() {
        return this.mljfsTelefone;
    }
    
    public void setMljfsTelefone(String mljfsTelefone) {
        this.mljfsTelefone = mljfsTelefone;
    }

    
    @Column(name="mljfs_setor")
    public String getMljfsSetor() {
        return this.mljfsSetor;
    }
    
    public void setMljfsSetor(String mljfsSetor) {
        this.mljfsSetor = mljfsSetor;
    }

    
    @Column(name="mljfs_senha", length=45)
    public String getMljfsSenha() {
        return this.mljfsSenha;
    }
    
    public void setMljfsSenha(String mljfsSenha) {
        this.mljfsSenha = mljfsSenha;
    }




}


