package bean;
// Generated 15/11/2023 20:40:24 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MljfsVendas generated by hbm2java
 */
@Entity
@Table(name=" mljfs_vendas"
    ,catalog="db_melany_salinas"
)
public class MljfsVendas  implements java.io.Serializable {

    /**
     * @return the mljfsMetodoPagamento
     */
   


     private int mljfsId;
     private MljfsClientes mljfsClientes;
     private MljfsFuncionarios mljfsFuncionarios;
     private Date mljfsData;
     private Date mljfsDataVenda;
     private Double mljfsValorTotal;
     private String mljfsMetodoPagamento;

    public MljfsVendas() {
    }

	
    public MljfsVendas(int mljfsId, Date mljfsData) {
        this.mljfsId = mljfsId;
        this.mljfsData = mljfsData;
    }
    public MljfsVendas(int mljfsId, MljfsClientes mljfsClientes, MljfsFuncionarios mljfsFuncionarios, Date mljfsData, Date mljfsDataVenda, Double mljfsValorTotal, String mljfsMetodoPagamento) {
       this.mljfsId = mljfsId;
       this.mljfsClientes = mljfsClientes;
       this.mljfsFuncionarios = mljfsFuncionarios;
       this.mljfsData = mljfsData;
       this.mljfsDataVenda = mljfsDataVenda;
       this.mljfsValorTotal = mljfsValorTotal;
       this.mljfsMetodoPagamento = mljfsMetodoPagamento;
    }
   
     @Id 

    
    @Column(name="mljfs_id", unique=true, nullable=false)
    public int getMljfsId() {
        return this.mljfsId;
    }
    
    public void setMljfsId(int mljfsId) {
        this.mljfsId = mljfsId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="mljfs_cliente_id")
    public MljfsClientes getMljfsClientes() {
        return this.mljfsClientes;
    }
    
    public void setMljfsClientes(MljfsClientes mljfsClientes) {
        this.mljfsClientes = mljfsClientes;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name=" mljfs_fk_funcionarios")
    public MljfsFuncionarios getMljfsFuncionarios() {
        return this.mljfsFuncionarios;
    }
    
    public void setMljfsFuncionarios(MljfsFuncionarios mljfsFuncionarios) {
        this.mljfsFuncionarios = mljfsFuncionarios;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="mljfs_data", nullable=false, length=10)
    public Date getMljfsData() {
        return this.mljfsData;
    }
    
    public void setMljfsData(Date mljfsData) {
        this.mljfsData = mljfsData;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="mljfs_data_venda", length=10)
    public Date getMljfsDataVenda() {
        return this.mljfsDataVenda;
    }
    
    public void setMljfsDataVenda(Date mljfsDataVenda) {
        this.mljfsDataVenda = mljfsDataVenda;
    }

    
    @Column(name=" mljfs_valor_total", precision=22, scale=0)
    public Double getMljfsValorTotal() {
        return this.mljfsValorTotal;
    }
    
    public void setMljfsValorTotal(Double mljfsValorTotal) {
        this.mljfsValorTotal = mljfsValorTotal;
    }


 public String getMljfsMetodoPagamento() {
        return mljfsMetodoPagamento;
    }

    /**
     * @param mljfsMetodoPagamento the mljfsMetodoPagamento to set
     */
    public void setMljfsMetodoPagamento(String mljfsMetodoPagamento) {
        this.mljfsMetodoPagamento = mljfsMetodoPagamento;
    }


}


