package bean;
// Generated 20/09/2023 18:06:06 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MljfsFuncionarios generated by hbm2java
 */
@Entity
@Table(name="mljfs_funcionarios"
    ,catalog="db_melany_salinas"
)
public class MljfsFuncionarios  implements java.io.Serializable {


     private int mljfsId;
     private String mljfsNome;
     private String mljfsCargo;
     private Double mljfsSalario;
     private Date mljfsDataAdmissao;
     private Date mljfsDataDemissao;
     private String mljfsTelefone;
     private String mljfsSetor;

    public MljfsFuncionarios() {
    }

	
    public MljfsFuncionarios(int mljfsId, String mljfsNome) {
        this.mljfsId = mljfsId;
        this.mljfsNome = mljfsNome;
    }
    public MljfsFuncionarios(int mljfsId, String mljfsNome, String mljfsCargo, Double mljfsSalario, Date mljfsDataAdmissao, Date mljfsDataDemissao, String mljfsTelefone, String mljfsSetor) {
       this.mljfsId = mljfsId;
       this.mljfsNome = mljfsNome;
       this.mljfsCargo = mljfsCargo;
       this.mljfsSalario = mljfsSalario;
       this.mljfsDataAdmissao = mljfsDataAdmissao;
       this.mljfsDataDemissao = mljfsDataDemissao;
       this.mljfsTelefone = mljfsTelefone;
       this.mljfsSetor = mljfsSetor;
    }
   
     @Id 

    
    @Column(name="mljfs_id", unique=true, nullable=false)
    public int getMljfsId() {
        return this.mljfsId;
    }
    
    public void setMljfsId(int mljfsId) {
        this.mljfsId = mljfsId;
    }

    
    @Column(name="mljfs_nome", nullable=false)
    public String getMljfsNome() {
        return this.mljfsNome;
    }
    
    public void setMljfsNome(String mljfsNome) {
        this.mljfsNome = mljfsNome;
    }

    
    @Column(name="mljfs_cargo")
    public String getMljfsCargo() {
        return this.mljfsCargo;
    }
    
    public void setMljfsCargo(String mljfsCargo) {
        this.mljfsCargo = mljfsCargo;
    }

    
    @Column(name="mljfs_salario", precision=10)
    public Double getMljfsSalario() {
        return this.mljfsSalario;
    }
    
    public void setMljfsSalario(Double mljfsSalario) {
        this.mljfsSalario = mljfsSalario;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="mljfs_data_admissao", length=10)
    public Date getMljfsDataAdmissao() {
        return this.mljfsDataAdmissao;
    }
    
    public void setMljfsDataAdmissao(Date mljfsDataAdmissao) {
        this.mljfsDataAdmissao = mljfsDataAdmissao;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="mljfs_data_demissao", length=10)
    public Date getMljfsDataDemissao() {
        return this.mljfsDataDemissao;
    }
    
    public void setMljfsDataDemissao(Date mljfsDataDemissao) {
        this.mljfsDataDemissao = mljfsDataDemissao;
    }

    
    @Column(name="mljfs_telefone", length=15)
    public String getMljfsTelefone() {
        return this.mljfsTelefone;
    }
    
    public void setMljfsTelefone(String mljfsTelefone) {
        this.mljfsTelefone = mljfsTelefone;
    }

    
    @Column(name="mljfs_setor")
    public String getMljfsSetor() {
        return this.mljfsSetor;
    }
    
    public void setMljfsSetor(String mljfsSetor) {
        this.mljfsSetor = mljfsSetor;
    }




}


