package bean;
// Generated 20/09/2023 18:06:06 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MljfsVendas generated by hbm2java
 */
@Entity
@Table(name="mljfs_vendas"
    ,catalog="db_melany_salinas"
)
public class MljfsVendas  implements java.io.Serializable {


     private int mljfsId;
     private MljfsClientes mljfsClientes;
     private Date mljfsData;
     private Date mljfsDataVenda;
     private String mljfsValorTotal;

    public MljfsVendas() {
    }

	
    public MljfsVendas(int mljfsId, Date mljfsData) {
        this.mljfsId = mljfsId;
        this.mljfsData = mljfsData;
    }
    public MljfsVendas(int mljfsId, MljfsClientes mljfsClientes, Date mljfsData, Date mljfsDataVenda, String mljfsValorTotal) {
       this.mljfsId = mljfsId;
       this.mljfsClientes = mljfsClientes;
       this.mljfsData = mljfsData;
       this.mljfsDataVenda = mljfsDataVenda;
       this.mljfsValorTotal = mljfsValorTotal;
    }
   
     @Id 

    
    @Column(name="mljfs_id", unique=true, nullable=false)
    public int getMljfsId() {
        return this.mljfsId;
    }
    
    public void setMljfsId(int mljfsId) {
        this.mljfsId = mljfsId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="mljfs_cliente_id")
    public MljfsClientes getMljfsClientes() {
        return this.mljfsClientes;
    }
    
    public void setMljfsClientes(MljfsClientes mljfsClientes) {
        this.mljfsClientes = mljfsClientes;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="mljfs_data", nullable=false, length=10)
    public Date getMljfsData() {
        return this.mljfsData;
    }
    
    public void setMljfsData(Date mljfsData) {
        this.mljfsData = mljfsData;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="mljfs_data_venda", length=10)
    public Date getMljfsDataVenda() {
        return this.mljfsDataVenda;
    }
    
    public void setMljfsDataVenda(Date mljfsDataVenda) {
        this.mljfsDataVenda = mljfsDataVenda;
    }

    
    @Column(name=" mljfs_valor_total", length=45)
    public String getMljfsValorTotal() {
        return this.mljfsValorTotal;
    }
    
    public void setMljfsValorTotal(String mljfsValorTotal) {
        this.mljfsValorTotal = mljfsValorTotal;
    }





}


