package bean;
// Generated 05/12/2023 08:44:27 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MljfsVendas generated by hbm2java
 */
@Entity
@Table(name="mljfs_vendas"
    ,catalog="db_melany_salinas"
)
public class MljfsVendas  implements java.io.Serializable {


     private int mljfsId;
     private int mljfsClienteId;
     private int mljfsFkFuncionarios;
     private Date mljfsData;
     private Double mljfsValorTotal;
     private String mljfsMetodoPagamento;

    public MljfsVendas() {
    }

	
    public MljfsVendas(int mljfsId, Date mljfsData) {
        this.mljfsId = mljfsId;
        this.mljfsData = mljfsData;
    }
    public MljfsVendas(int mljfsId, int mljfsClienteId, int mljfsFkFuncionarios, Date mljfsData, Double mljfsValorTotal, String mljfsMetodoPagamento, Set mljfsVendasProdutoses) {
       this.mljfsId = mljfsId;
       this.mljfsClienteId = mljfsClienteId;
       this.mljfsFkFuncionarios = mljfsFkFuncionarios;
       this.mljfsData = mljfsData;
       this.mljfsValorTotal = mljfsValorTotal;
       this.mljfsMetodoPagamento = mljfsMetodoPagamento;
      // this.mljfsVendasProdutoses = mljfsVendasProdutoses;
    }
   
     @Id 

    
    @Column(name="mljfs_id", unique=true, nullable=false)
    public int getMljfsId() {
        return this.mljfsId;
    }
    
    public void setMljfsId(int mljfsId) {
        this.mljfsId = mljfsId;
    }

    
    @Column(name="mljfs_cliente_id")
    public int getMljfsClienteId() {
        return this.mljfsClienteId;
    }
    
    public void setMljfsClienteId(int mljfsClienteId) {
        this.mljfsClienteId = mljfsClienteId;
    }

    
    @Column(name="mljfs_fk_funcionarios")
    public int getMljfsFkFuncionarios() {
        return this.mljfsFkFuncionarios;
    }
    
    public void setMljfsFkFuncionarios(int mljfsFkFuncionarios) {
        this.mljfsFkFuncionarios = mljfsFkFuncionarios;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="mljfs_data", nullable=false, length=10)
    public Date getMljfsData() {
        return this.mljfsData;
    }
    
    public void setMljfsData(Date mljfsData) {
        this.mljfsData = mljfsData;
    }

    
    @Column(name="mljfs_valor_total", precision=22, scale=0)
    public Double getMljfsValorTotal() {
        return this.mljfsValorTotal;
    }
    
    public void setMljfsValorTotal(Double mljfsValorTotal) {
        this.mljfsValorTotal = mljfsValorTotal;
    }

    
    @Column(name="mljfs_metodo_pagamento", length=45)
    public String getMljfsMetodoPagamento() {
        return this.mljfsMetodoPagamento;
    }
    
    public void setMljfsMetodoPagamento(String mljfsMetodoPagamento) {
        this.mljfsMetodoPagamento = mljfsMetodoPagamento;
    }






}


