package bean;
// Generated 15/11/2023 20:40:24 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MljfsVendasProdutos generated by hbm2java
 */
@Entity
@Table(name="mljfs_vendas_produtos"
    ,catalog="db_melany_salinas"
)
public class MljfsVendasProdutos  implements java.io.Serializable {


     private int mljfsId;
     private MljfsVendas mljfsVendas;
     private int mljfsQuantidade;
     private Double mljfsPrecoUnitario;
     private Double mljfsPrecoTotal;

    public MljfsVendasProdutos() {
    }

	
    public MljfsVendasProdutos(int mljfsId) {
        this.mljfsId = mljfsId;
    }
    public MljfsVendasProdutos(int mljfsId, MljfsVendas mljfsVendas, int mljfsQuantidade, Double mljfsPrecoUnitario, Double mljfsPrecoTotal) {
       this.mljfsId = mljfsId;
       this.mljfsVendas = mljfsVendas;
       this.mljfsQuantidade = mljfsQuantidade;
       this.mljfsPrecoUnitario = mljfsPrecoUnitario;
       this.mljfsPrecoTotal = mljfsPrecoTotal;
    }
   
     @Id 

    
    @Column(name="mljfs_id", unique=true, nullable=false)
    public int getMljfsId() {
        return this.mljfsId;
    }
    
    public void setMljfsId(int mljfsId) {
        this.mljfsId = mljfsId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="mljfs_fk_vendas")
    public MljfsVendas getMljfsVendas() {
        return this.mljfsVendas;
    }
    
    public void setMljfsVendas(MljfsVendas mljfsVendas) {
        this.mljfsVendas = mljfsVendas;
    }

    
    @Column(name="mljfs_quantidade")
    public int getMljfsQuantidade() {
        return this.mljfsQuantidade;
    }
    
    public void setMljfsQuantidade(int mljfsQuantidade) {
        this.mljfsQuantidade = mljfsQuantidade;
    }

    
    @Column(name="mljfs_preco_unitario", precision=10)
    public Double getMljfsPrecoUnitario() {
        return this.mljfsPrecoUnitario;
    }
    
    public void setMljfsPrecoUnitario(Double mljfsPrecoUnitario) {
        this.mljfsPrecoUnitario = mljfsPrecoUnitario;
    }

    
    @Column(name="mljfs_preco_total", precision=10)
    public Double getMljfsPrecoTotal() {
        return this.mljfsPrecoTotal;
    }
    
    public void setMljfsPrecoTotal(Double mljfsPrecoTotal) {
        this.mljfsPrecoTotal = mljfsPrecoTotal;
    }




}


